services:
  db:
    container_name: pharmacy_db
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pharmacy
    ports:
      - '5435:5432'
    volumes:
      - pharmacy_data:/var/lib/postgresql/data
volumes:
  pharmacy_data: {}
